# Only install packages released at least 7 days ago
minimumReleaseAge: 10080
strictPeerDependencies: true

packages:
  - "apps/*"
  - "packages/*"

peerDependencyRules:
  allowedVersions:
    "typescript": "5.9.2"
